<?php 
$bancos = [
    "001 - Banco do Brasil S.A.",
    "033 - Banco Santander (Brasil) S.A.",
    "104 - Caixa Econômica Federal",
    "237 - Banco Bradesco S.A.",
    "341 - Banco Itaú S.A.",
    "389 - Banco Mercantil do Brasil S.A.",
    "422 - Banco Safra S.A.",
    "748 - Banco Cooperativo Sicredi S.A.",
    "756 - Banco Cooperativo do Brasil S.A. - Bancoob",
    "212 - Banco Original S.A.",
    "077 - Banco Inter S.A.",
    "260 - Nu Pagamentos S.A. (Nubank)",
    "637 - Banco Sofisa S.A.",
    "655 - Banco Votorantim S.A.",
    "364 - Banco C6 S.A.",
    "336 - Banco Crefisa S.A.",
    "741 - Banco Ribeirão Preto S.A.",
    "743 - Banco Semear S.A.",
    "652 - Itaú Unibanco Holding S.A.",
    "637 - Banco Sofisa S.A.",
    "655 - Banco Votorantim S.A.",
    "364 - Banco C6 S.A.",
    "336 - Banco Crefisa S.A.",
    "741 - Banco Ribeirão Preto S.A.",
    "743 - Banco Semear S.A.",
    "131 - Tullett Prebon Brasil Corretora de Valores e Câmbio Ltda.",
    "011 - Credit Suisse Hedging-Griffo Corretora de Valores S.A.",
    "611 - Banco Paulista S.A.",
    "604 - Banco Industrial do Brasil S.A.",
    "630 - Banco Smartbank S.A.",
    "243 - Banco Máxima S.A.",
    "654 - Banco A.J.Renner S.A.",
    "212 - Banco Original S.A.",
    "077 - Banco Inter S.A.",
    "260 - Nu Pagamentos S.A. (Nubank)",
    "637 - Banco Sofisa S.A.",
    "655 - Banco Votorantim S.A.",
    "364 - Banco C6 S.A.",
    "336 - Banco Crefisa S.A.",
    "741 - Banco Ribeirão Preto S.A.",
    "743 - Banco Semear S.A.",
    "652 - Itaú Unibanco Holding S.A.",
    "637 - Banco Sofisa S.A.",
    "655 - Banco Votorantim S.A.",
    "364 - Banco C6 S.A.",
    "336 - Banco Crefisa S.A.",
    "741 - Banco Ribeirão Preto S.A.",
    "743 - Banco Semear S.A.",
    "131 - Tullett Prebon Brasil Corretora de Valores e Câmbio Ltda.",
    "011 - Credit Suisse Hedging-Griffo Corretora de Valores S.A.",
    "611 - Banco Paulista S.A.",
    "604 - Banco Industrial do Brasil S.A.",
    "630 - Banco Smartbank S.A.",
    "243 - Banco Máxima S.A.",
    "654 - Banco A.J.Renner S.A."
];

?>