-- CRIAR TABELA
-- QUE RECEBE O ID DO PROJETO E A SOLICITACAO DE INATIVAR PROJETO DE ONG
-- VERIFICAR AS TABELAS QUE GUARDA AS INFORMAÇOES DE PROJETO INATIVO
-- E OS MOTIVO/ SETAR A TABELA DE INATIVAR PROJETO DE ONG
-- PENSAR EM UM NOME AONDE BUSCA TODOS OS MOTIVOS DE INATIVAR PROJETO
-- EXEMPLO / ATENDIDO / RECUSADO 
-- POR FINAL UPDATE DO MOTIVO DE INATIVAR PROJETO
-- NA TABELA DE ONGS OU ALGUMA TABELA QUE GUARDA AS INFORMAÇOES DE PROJETO INATIVO

UPDATE tabela/acriar/ 

UPDATE tabela/status/

UPDATE tabela/imagens/

